# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4bc43df7d70520b7d5962e2ac062eab929dd127a3f9a78c95fe6f78d3246cedd55c06400495a3836dcd742f5f9f691f5c495f17b53f4227094855bf969e09eb

test:
  secret_key_base: 7200c1feb0ed0968ed0873d67b3165a52f35077e413a8d8f4d3c75865a873d9c809604bac05d282d94d32b9d4a4b71cfd3d452a9e21d955c6f73045922754897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
